# Generated by Django 4.2.2 on 2023-06-26 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models.webhook
import main.models.webhook_call


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker",
                    models.CharField(
                        choices=[("IBKR", "Interactive Brokers")], default="IBKR"
                    ),
                ),
                ("name", models.CharField(default="")),
                ("oauth_consumer_key", models.CharField(default="")),
                ("oauth_token", models.CharField(default="")),
                ("oauth_token_secret", models.TextField(default="")),
                ("dh_params", models.TextField(default="")),
                ("signature_key", models.TextField(default="")),
                ("encryption_key", models.TextField(default="")),
                ("live_session_token", models.CharField(blank=True, default="")),
                (
                    "live_session_token_expiration",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("user_uid", models.CharField(blank=True, default="")),
                ("account_uid", models.CharField(blank=True, default="")),
                ("paper", models.BooleanField(default=False)),
                ("last_success", models.DateTimeField(editable=False, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "uid",
                    models.CharField(
                        default=main.models.webhook.hex_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ORDER", "Place order"),
                            ("PREVIEW", "Preview order"),
                        ],
                        default="PREVIEW",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.connection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookCall",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=main.models.webhook_call.hex_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_ip", models.GenericIPAddressField()),
                ("method", models.CharField(max_length=10)),
                ("request_headers", models.TextField(blank=True, null=True)),
                ("request_body", models.TextField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(default=None, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.webhook"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="APICall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("url", models.URLField()),
                ("method", models.CharField(max_length=10)),
                ("request_headers", models.TextField(blank=True, null=True)),
                ("request_body", models.TextField(blank=True, null=True)),
                ("response_status", models.PositiveIntegerField(blank=True, null=True)),
                ("response_headers", models.TextField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, null=True)),
                ("duration", models.FloatField(null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.connection",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.webhook",
                    ),
                ),
                (
                    "webhook_call",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_calls",
                        to="main.webhookcall",
                    ),
                ),
            ],
        ),
    ]
