# Generated by Django 4.2.2 on 2023-06-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookcall",
            name="client_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
