# Generated by Django 4.2.2 on 2023-07-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_webhookcall_client_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicall",
            name="response_status",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="mode",
            field=models.CharField(
                choices=[
                    ("ORDER", "Place order"),
                    ("PREVIEW", "Preview order"),
                    ("TG_ALERT", "Telegram alert"),
                ],
                default="PREVIEW",
            ),
        ),
    ]
